name: Build and Push Docker Image

on:
    push:
        branches:
            - feature/aws-docker-integration


jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
        
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: log in to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build Docker image
            run: |
              docker build -t ${{secrets.DOCKER_USERNAME}}/node-app:v${{github.run_number}} .
          
          - name: Push Docker image
            run: |
              docker push ${{secrets.DOCKER_USERNAME}}/node-app:v${{github.run_number}}
    
    deploy:

      runs-on: ubuntu-latest

      steps:
         - name: Set up SSh keys
           run: |
             echo "${{secrets.EC2_SSH_KEY}}" > private_key.pem
             chmod 400 private_key.pem

         - name: Connect to EC2 and deploy
           run: |
             ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-52-87-168-29.compute-1.amazonaws.com << 'EOF'
             sudo dnf install -y docker
             sudo systemctl start docker
             sudo systemctl enable docker
             sudo dnf install -y jq
             LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/node-app/tags/?page_size=1 | jq -r '.results[0].name')
             docker pull ${{ secrets.DOCKER_USERNAME }}/node-app:$LATEST_TAG
             docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/node-app:$LATEST_TAG
             EOF